### ISSUE TITLE
Disable based on number of lines

### ISSUE THREAD

**Issue by ragu-manjegowda** [LunarVim/bigfile.nvim#11]
Will it be possible to add option to disable features (enable this plugin) based on number of lines?

For example, a python file with 5k lines of code will be hardly 200Kb in size yet insanely slow.

**Comment by JosefLitos** [comment]
This would require to parse the file contents first, which is the reason why it is slow in the first place. Using just size allows it to get the filesize from the system without ever viewing the contents of the file, allowing it to react in constant time.

**Comment by ragu-manjegowda** [comment]
Not sure if I agree, treesitter parsing the syntax is not same as just counting the lines.

Also, this need not be default, user will be opting in for this knowingly.

There are many plugins that make use of this API already - vim.api.nvim_buf_line_count(0)

Combining line count with filetype will definitely be very helpful.

**Comment by ragu-manjegowda** [comment]
Or you can just expose a hook to function that can return bool. 

This way it is on user decide when/how to disable.

**Comment by LostNeophyte** [comment]
> Or you can just expose a hook to function that can return bool.
> 
> This way it is on user decide when/how to disable.

This is probably the way i'll do it, since you might want the line count to work based on a filetype or even more factors

`function override_detection(bufnr: number, filesize_mib: number, bigfile_detected: bool): bool|nil`
if the function doesn't return anything, just the filezise will be used, otherwise the returned boolean will be used (true -> file is big, disable features | false -> do nothing)

what do you think?

**Comment by ragu-manjegowda** [comment]
Perfect, sounds good to me. Thank you very much!
